In [1]:
!pip install numpy

In [5]:
import numpy as np
np1 = np.array([[1,2,3],[3,2,1]])
print(np1)
print(np1.ndim) #維度
print(np1.shape) #形狀
print(np1.dtype)#資料型别

[[1 2 3]
 [3 2 1]]
2
(2, 3)
int32


In [6]:
import numpy as np
np2 = np.array([[1,2,3],[3,2,1],[3,3,3]])
print(np2)
print(np2.ndim) #維度
print(np2.shape) #形狀
print(np2.dtype)#資料型别

[[1 2 3]
 [3 2 1]
 [3 3 3]]
2
(3, 3)
int32


In [8]:
np_0=np.zeros([3,2],int)#([列數,欄數],dtype)
np_1=np.ones([4,3],int)#([列數,欄數],dtype)
print(np_0)
print(np_1)

[[0 0]
 [0 0]
 [0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [11]:
np1=np.full((3,2),4)#(形狀,填充值,dtype=資料型態)
np2=np.eye(6)#(大小,M=指定col,k=起始位置,dtype=資料型態)
print(np1)
print(np2)

[[4 4]
 [4 4]
 [4 4]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [12]:
np3 = np.eye(6, M=8, k=2) #6*8的矩陣
print(np3)

[[0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [18]:
#(起始值,停止值,生成數量,結尾值(0包含1不包含結尾),回傳模式,資料型態)
np1=np.linspace(1,10,5,1,0,dtype=int)
np2=np.linspace(1,10,5,1,1,dtype=float)
np22=np.linspace(1,10,5,0,1,dtype=float) #回傳模式提供間距值
np3=np.linspace(1,10,5,0,0,dtype=int)
#(起始值,停止值,間距,資料型態)
np4=np.arange(10) #結尾值不包含
print(np1)
print(np2)
print(np22)
print(np3)
print(np4)

[ 1  3  5  7 10]
(array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]), 2.25)
(array([1. , 2.8, 4.6, 6.4, 8.2]), 1.8)
[1 2 4 6 8]
[0 1 2 3 4 5 6 7 8 9]


In [19]:
np1 = np.array([1,2,3])
np2 = np.array([[1,2,3,4],[5,6,7,8]])
print(np1[1])
print(np1[0:2]) #不包含尾
print(np2[1,2])
print(np2[1][2])
print(np2[[1,1],[0,2]]) #[1,0][1,2]

2
[1 2]
7
7
[5 7]


In [22]:
np1 = np.array([[1,2,3],[4,5,6]])
np2 = np.array([[3,2,1],[7,6,5]])
print(np1+np2)
print(np1-np2)
print("-----")
print(np1*np2)
print(np1/np2)
print(np.round(np1/np2, decimals=2)) #取位數

[[ 4  4  4]
 [11 11 11]]
[[-2  0  2]
 [-3 -1  1]]
-----
[[ 3  4  3]
 [28 30 30]]
[[0.33333333 1.         3.        ]
 [0.57142857 0.83333333 1.2       ]]
[[0.33 1.   3.  ]
 [0.57 0.83 1.2 ]]


In [23]:
data1= np.array([[1,2,3],[4,5,6],[7,8,9]])
data2= np.array([[5,6,7,8],[9,10,11,12],[6,7,8,9]])
print(np.dot(data1,data2))
print(data1.dot(data2)) #兩種寫法

[[ 41  47  53  59]
 [101 116 131 146]
 [161 185 209 233]]
[[ 41  47  53  59]
 [101 116 131 146]
 [161 185 209 233]]


In [25]:
np1 = np.array([[1,2,3],[4,5,6]])
np2 = np.array([[7,8,9],[3,4,5]])
print(np1)
print(np2)
print(np.inner(np1,np2))
#[1,2,3]*[7,8,9]  [1,2,3]*[3,4,5]
#[4,5,6]*[7,8,9]  [4,5,6]*[3,4,5]


[[1 2 3]
 [4 5 6]]
[[7 8 9]
 [3 4 5]]
[[ 50  26]
 [122  62]]


In [27]:
np1 = np.array([1,2,3])
np2 = np.array([7, 8])
print(np1)
print(np2)
print(np.outer(np1,np2))

[1 2 3]
[7 8]
[[ 7  8]
 [14 16]
 [21 24]]
